package com.caschigialli.api.enums;

public enum Permission {
    VIEW_ADMIN_DETAILS,
    VIEW_USER_DETAILS,
    VIEW_CUSTOMER_DETAILS,
    MANAGE_CUSTOMER_DATA,
    VIEW_SUPPLIER_DETAILS,
    MANAGE_SUPPLIER_DATA,
    SEND_EMAIL,
    SEND_MESSAGE_TO_CUSTOMER,
    SEND_MESSAGE_TO_SUPPLIER,
    SEND_MESSAGE,
    CREATE_USER
}
